<template>
  <div class="loadingio-spinner-eclipse-apxv8otbi6d"><div class="ldio-1wllw7yzbe9">
    <div></div>
  </div></div>
</template>

<script>
export default {
  name: 'LoadingSpinner'
}
</script>

<style type="text/css">
  @keyframes ldio-1wllw7yzbe9 {
    0% { transform: rotate(0deg) }
    50% { transform: rotate(180deg) }
    100% { transform: rotate(360deg) }
  }
  .ldio-1wllw7yzbe9 div {
    position: absolute;
    animation: ldio-1wllw7yzbe9 1.02s linear infinite;
    width: 100px;
    height: 100px;
    top: 20.4px;
    left: 20.4px;
    border-radius: 50%;
    box-shadow: 0 4.08px 0 0 #ffffff;
    transform-origin: 81.6px 83.64px;
  }
  .loadingio-spinner-eclipse-apxv8otbi6d {
    width: 150px;
    height: 150px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-1wllw7yzbe9 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-1wllw7yzbe9 div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>