<template>
  <div class="loadingio-spinner-spinner-hlxf8sozyvv"><div class="ldio-xy3tpc9pusq">
  <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
  </div></div>
</template>

<script>
export default {
  name: 'LoadingSpinner'
}
</script>

<style type="text/css">
  @keyframes ldio-xy3tpc9pusq {
    0% { opacity: 1 }
    100% { opacity: 0 }
  }
  .ldio-xy3tpc9pusq div {
    left: 94px;
    top: 46px;
    position: absolute;
    animation: ldio-xy3tpc9pusq linear 1s infinite;
    background: #f5f5f5;
    width: 12px;
    height: 28px;
    border-radius: 6px / 14px;
    transform-origin: 6px 54px;
  }.ldio-xy3tpc9pusq div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.9166666666666666s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(2) {
    transform: rotate(30deg);
    animation-delay: -0.8333333333333334s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(3) {
    transform: rotate(60deg);
    animation-delay: -0.75s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(4) {
    transform: rotate(90deg);
    animation-delay: -0.6666666666666666s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(5) {
    transform: rotate(120deg);
    animation-delay: -0.5833333333333334s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(6) {
    transform: rotate(150deg);
    animation-delay: -0.5s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(7) {
    transform: rotate(180deg);
    animation-delay: -0.4166666666666667s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(8) {
    transform: rotate(210deg);
    animation-delay: -0.3333333333333333s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(9) {
    transform: rotate(240deg);
    animation-delay: -0.25s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(10) {
    transform: rotate(270deg);
    animation-delay: -0.16666666666666666s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(11) {
    transform: rotate(300deg);
    animation-delay: -0.08333333333333333s;
    background: #f5f5f5;
  }.ldio-xy3tpc9pusq div:nth-child(12) {
    transform: rotate(330deg);
    animation-delay: 0s;
    background: #f5f5f5;
  }
  .loadingio-spinner-spinner-hlxf8sozyvv {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: none;
    margin: 0 auto;
  }
  .ldio-xy3tpc9pusq {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-xy3tpc9pusq div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>